from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.fields.html5 import DateField
from wtforms.validators import InputRequired, Optional


class new_event_form(FlaskForm):
    player_name = StringField('Your Name', validators=[InputRequired()])
    mtgformat = StringField('Format', validators=[InputRequired()])
    deck_name = StringField('Deck Name', validators=[InputRequired()])
    event_date = DateField('Date', validators=[InputRequired()])
    event_rounds = IntegerField('Round')
    first_oppname = StringField('Opponent Name', validators=[InputRequired()])
    first_oppdeck = StringField('Deck Name', validators=[InputRequired()])
    first_w = IntegerField('Games Won', validators=[InputRequired()])
    first_d = IntegerField('Games Drawn', validators=[InputRequired()])
    first_l = IntegerField('Games Lost', validators=[InputRequired()])
    second_oppname = StringField('Opponent Name')
    second_oppdeck = StringField('Deck Name')
    second_w = IntegerField('Games Won', validators=[Optional(strip_whitespace=True)])
    second_d = IntegerField('Games Drawn', validators=[Optional(strip_whitespace=True)])
    second_l = IntegerField('Games Lost', validators=[Optional(strip_whitespace=True)])
    third_oppname = StringField('Opponent Name')
    third_oppdeck = StringField('Deck Name')
    third_w = IntegerField('Games Won', validators=[Optional(strip_whitespace=True)])
    third_d = IntegerField('Games Drawn', validators=[Optional(strip_whitespace=True)])
    third_l = IntegerField('Games Lost', validators=[Optional(strip_whitespace=True)])
    fourth_oppname = StringField('Opponent Name')
    fourth_oppdeck = StringField('Deck Name')
    fourth_w = IntegerField('Games Won', validators=[Optional(strip_whitespace=True)])
    fourth_d = IntegerField('Games Drawn', validators=[Optional(strip_whitespace=True)])
    fourth_l = IntegerField('Games Lost', validators=[Optional(strip_whitespace=True)])
    fifth_oppname = StringField('Opponent Name')
    fifth_oppdeck = StringField('Deck Name')
    fifth_w = IntegerField('Games Won', validators=[Optional(strip_whitespace=True)])
    fifth_d = IntegerField('Games Drawn', validators=[Optional(strip_whitespace=True)])
    fifth_l = IntegerField('Games Lost', validators=[Optional(strip_whitespace=True)])
    eventstatusinput = StringField('Event Status:')
    eventrecordinput = StringField('Event Record (Win/Draw/Loss):')
    eventgamewin = StringField('Event Game Win %:')
